@startuml diagrama

class Humano
class Serie{
    - Foco : focos[10]
    + EncenderTodo()
    + Imprimir()
}
class Foco{
    - EstadoFoco : estadoActual
    + Encender()
    + Apagar()
    + LeerEstado() : EstadoFoco
}
class EstadoFoco
class Booleano

Serie "1" *-- "10" Foco
EstadoFoco --|> Booleano
Humano o-- Foco 
Foco *-- EstadoFoco
Humano "1" o-- "1" Serie



@enduml